#include <iostream.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <limits.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include "semaphore.h"

const int MAXCHAR = 10;
const int BUFFSIZE = 3;
enum {PUT_ITEM, TAKE_ITEM}; // set up names of my 2 semaphores

void producer_proc(SEMAPHORE &, char *);
void parent_cleanup(SEMAPHORE &, int);
void consumer_proc(SEMAPHORE &, char *);

int main(){
	int shmid;
	char *shmBUF;

	SEMAPHORE sem(2); //(2) value of semaphores
	sem.V(PUT_ITEM); //+1
	sem.V(PUT_ITEM); //+1
	sem.V(PUT_ITEM); //+1
					 //3 (initial value)

	//SHARED MEMORY
	shmid = shmget(IPC_PRIVATE, BUFFSIZE*sizeof(char), PERMS); //IPC_PRIVATE - In Linux generates an autogenerated key (lazy way/convenient that replaces the ftok function)
	shmBUF = (char *)shmat(shmid, 0, SHM_RND);

	if(fork()){ /* parent process */

		producer_proc(sem, shmBUF);
		parent_cleanup(sem, shmid);

	} else { // child process -- inherits everything the parent process already has
		consumer_proc(sem, shmBUF);
	}

	exit(0);
} // main

void consumer_proc(SEMAPHORE &sem, char *shmBUF) {
	char tmp;

	for(int k=0; k<MAXCHAR; k++){
		sem.P(TAKE_ITEM); //sem.P is the object and TAKE_ITEM is the semaphore that corresponds to 1
		tmp = *(shmBUF+k%BUFFSIZE); //take
		sem.V(PUT_ITEM); //sem.V is the ojects and PUT_ITEM is the semaphore that corresponds to 0
		cout << "(" << getpid() << ")  " 
				<< "buf[" << k%BUFFSIZE << "] "
				<< tmp << endl;
	}
} // child_proc

void producer_proc(SEMAPHORE &sem, char *shmBUF) {

	char data[128];
	cout << "(" << getpid() << ")  Please enter a string --> ";
	cin.getline(data, 127);

	char input;
	for(int k=0; k<MAXCHAR; k++){
		input = data[k]; //produce item
		sem.P(PUT_ITEM); 
		*(shmBUF+(k%BUFFSIZE)) = input; //copy to buffer -- k % BUFFSIZE ranges from 0-2 and then loops again
		sem.V(TAKE_ITEM); //consumer will get a chance to use this item
	}
} // parent_proc

void parent_cleanup (SEMAPHORE &sem, int shmid) {

	int status;			/* child status */
	wait(0);	/* wait for child to exit */
	shmctl(shmid, IPC_RMID, NULL);	/* cleaning up */
	sem.remove(); //deallocate the semaphores (need to call that explicitly)
} // parent_cleanup

